AWSTemplateFormatVersion: 2010-09-09
Description: s3 bucket creation

Parameters:
  BucketName: 
    Type: String
    Description: Enter Bucket name

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      